//HintName: GeneratedHierarchy.g.cs
// <auto-generated/>
using Amusoft.Toolkit.System.CommandLine.CommandModel;

namespace Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator;

public static class GeneratedHierarchy
{
	public static readonly ICommandHierarchy MixedChainParent = 
		CommandHierarchyBuilder.FromArray(new[,]
		{
			{typeof(Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator.MixedChainParent), typeof(Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator.MixedChainChild1)},
			{typeof(Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator.MixedChainChild1), typeof(Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator.MixedChainChild2)},
		});
}