//HintName: GeneratedHierarchy.g.cs
// <auto-generated/>
using Amusoft.Toolkit.System.CommandLine.CommandModel;

namespace Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator;

public static class GeneratedHierarchy
{
	public static readonly ICommandHierarchy ParallelChainParent = 
		CommandHierarchyBuilder.FromArray(new[,]
		{
			{typeof(Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator.ParallelChainParent), typeof(Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator.ParallelChainChild1)},
			{typeof(Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator.ParallelChainChild1), typeof(Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator.ParallelChainChild2)},
		});
	public static readonly ICommandHierarchy Parallel2ChainParent = 
		CommandHierarchyBuilder.FromArray(new[,]
		{
			{typeof(Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator.Parallel2ChainParent), typeof(Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator.Parallel2ChainChild1)},
			{typeof(Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator.Parallel2ChainChild1), typeof(Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator.Parallel2ChainChild2)},
		});
}