//HintName: GeneratedHierarchy.g.cs
// <auto-generated/>
using Amusoft.Toolkit.System.CommandLine.CommandModel;

namespace Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator;

public static class GeneratedHierarchy
{
	public static readonly ICommandHierarchy ParentCommand = 
		CommandHierarchyBuilder.FromArray(new[,]
		{
			{typeof(Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator.ParentCommand), typeof(Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator.Child1Command)},
			{typeof(Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator.ParentCommand), typeof(Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator.Child2Command)},
		});
}