//HintName: MixedCommandNoParameter.g.cs
// <auto-generated/>

using System.CommandLine;
using System.CommandLine.Invocation;
using System.Threading.Tasks;
using Amusoft.Toolkit.System.CommandLine.Attributes;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace Amusoft.Toolkit.System.CommandLine.UnitTests.TestResources.ExecuteHandlerGenerator;	

internal partial class MixedCommandNoParameter : MixedCommandNoParameter.ICommandInvoker
{		
	private void BindHandler()
	{
		this.SetHandler(async (context) =>
		{
			
			await ((MixedCommandNoParameter.ICommandInvoker)this).ExecuteAsync(context);
		});
	}

	internal interface ICommandInvoker
	{
		public abstract Task ExecuteAsync(InvocationContext context);
	}
}